/**
 * download-audio.mjs
 *
 * Reads all data files, finds entries that are missing an audioFile,
 * downloads the audio from YouTube using yt-dlp, saves as .webm,
 * and updates the audioFile field in the data file.
 *
 * Uses proper JSON parsing (not regex) to read/write data files.
 *
 * Run: node scripts/download-audio.mjs
 * Called automatically by: .github/workflows/daily-rebuild.yml
 */

import { execSync, spawnSync } from 'child_process'
import { writeFileSync, readFileSync, existsSync, renameSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const DATA_DIR = join(ROOT, 'src', 'data')
const AUDIO_DIR = join(ROOT, 'public', 'audio')

const MONTH_KEYS = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december'
]

const MONTH_NAMES_ALB = [
  'Janar', 'Shkurt', 'Mars', 'Prill', 'Maj', 'Qershor',
  'Korrik', 'Gusht', 'Shtator', 'Tetor', 'Nëntor', 'Dhjetor'
]

function getYtDlpPath() {
  for (const c of ['yt-dlp', 'yt-dlp.exe']) {
    try {
      execSync(`${c} --version`, { stdio: 'pipe' })
      return c
    } catch {}
  }
  return 'yt-dlp'
}

// Read a month data file and return its entries as a parsed array
function readMonthData(filePath) {
  const content = readFileSync(filePath, 'utf8')
  const match = content.match(/export const \w+ = (\[[\s\S]*\])/)
  if (!match) return null
  try {
    return JSON.parse(match[1])
  } catch {
    return null
  }
}

// Write a month data file from its entries array
function writeMonthData(filePath, exportName, entries) {
  const content = [
    `// Auto-generated by scripts/fetch-playlist.mjs — do not edit manually`,
    `export const ${exportName} = ${JSON.stringify(entries, null, 2)}`,
  ].join('\n') + '\n'
  writeFileSync(filePath, content, 'utf8')
}

const ytdlp = getYtDlpPath()
let anyDownloaded = false

mkdirSync(AUDIO_DIR, { recursive: true })

for (let i = 0; i < MONTH_KEYS.length; i++) {
  const monthKey = MONTH_KEYS[i]
  const monthName = MONTH_NAMES_ALB[i]
  const filePath = join(DATA_DIR, `${monthKey}.js`)

  if (!existsSync(filePath)) continue

  const entries = readMonthData(filePath)
  if (!entries) {
    console.warn(`⚠ Could not parse ${monthKey}.js — skipping`)
    continue
  }

  let updated = false

  for (const entry of entries) {
    if (!entry.videoId) continue
    if (entry.audioFile) continue  // already has audio

    const audioFilename = `${monthKey}-${entry.day}.webm`
    const audioPath = join(AUDIO_DIR, audioFilename)

    // If file already exists on disk, just update the data entry
    if (existsSync(audioPath)) {
      console.log(`  ℹ ${audioFilename} already on disk — adding to data file`)
    } else {
      console.log(`⬇ Downloading audio for ${entry.day} ${monthName} (${entry.videoId})…`)
      const cookiesFile = process.env.COOKIES_FILE
      const url = `https://www.youtube.com/watch?v=${entry.videoId}`
      const outputTpl = audioPath.replace('.webm', '.%(ext)s')

      // Try multiple strategies — YouTube's n-challenge can block downloads
      const strategies = [
        { label: 'opus + ejs:github',
          args: ['-x', '--audio-format', 'opus', '--remote-components', 'ejs:github'] },
        { label: 'opus + web client',
          args: ['-x', '--audio-format', 'opus', '--extractor-args', 'youtube:player_client=web'] },
        { label: 'bestaudio + ejs:github',
          args: ['-f', 'bestaudio', '--remote-components', 'ejs:github'] },
        { label: 'bestaudio + default',
          args: ['-f', 'bestaudio'] },
      ]

      let downloaded = false
      for (const { label, args: baseArgs } of strategies) {
        const dlArgs = [...baseArgs]
        if (cookiesFile) dlArgs.push('--cookies', cookiesFile)
        dlArgs.push('-o', outputTpl, url)
        const result = spawnSync(ytdlp, dlArgs, { encoding: 'utf8', stdio: 'inherit' })

        // Check if any output file was created (yt-dlp may save as .opus or .webm)
        const opusPath = audioPath.replace('.webm', '.opus')
        if (existsSync(opusPath) || existsSync(audioPath)) {
          console.log(`  ✓ Strategy "${label}" succeeded`)
          downloaded = true
          break
        }
        console.log(`  ⚠ Strategy "${label}" failed, trying next…`)
      }

      // yt-dlp may save as .opus — rename to .webm for consistency
      const opusPath = audioPath.replace('.webm', '.opus')
      if (existsSync(opusPath)) {
        renameSync(opusPath, audioPath)
        console.log(`  ✓ Saved as ${audioFilename}`)
      } else if (!existsSync(audioPath)) {
        if (!downloaded) {
          console.warn(`  ✗ All download strategies failed for ${entry.videoId} — skipping`)
        } else {
          console.warn(`  ✗ Download reported success but file not found for ${entry.videoId} — skipping`)
        }
        continue
      }
    }

    entry.audioFile = audioFilename
    updated = true
    anyDownloaded = true
    console.log(`  ✓ Updated data file with audioFile: ${audioFilename}`)
  }

  if (updated) {
    writeMonthData(filePath, monthKey, entries)
    console.log(`✓ Saved ${monthKey}.js`)
  }
}

if (!anyDownloaded) {
  console.log('✅ All entries already have audio — nothing to do.')
} else {
  console.log('\n✅ Done. New audio files ready to commit.')
}
